'use client';
import Link from 'next/link';
import { useCallback,useEffect,useRef,useState } from 'react';
import { PAGE_FIELDS,type Block,type DocumentContent } from '@/lib/studio/schema';
import styles from './Studio.module.css';
type Doc={id:string;title:string;slug:string;kind:string;status:string;version:number;content:DocumentContent};
type Revision={id:string;number:number;reason:string;created_at:string};
type Note={id:string;code:string|null;domain:string;severity:string;body:string;resolved:boolean};
type EditorialContent=Extract<DocumentContent,{kind:'article'|'case'}>;
function EditorialFields({content,onChange,relatedOptions,mediaOptions}:{content:EditorialContent;onChange:(value:EditorialContent)=>void;relatedOptions:{id:string;title:string;kind:string}[];mediaOptions:{id:string;alt:string}[]}){
  return <section><h2>Credits, sources and media</h2>
    <label>Tags (one per line)<textarea value={content.tags.join('\n')} onChange={e=>onChange({...content,tags:e.target.value.split('\n').map(v=>v.trim()).filter(Boolean)})}/></label>
    <label>Author name<input value={content.byline?.name??''} onChange={e=>onChange({...content,byline:e.target.value?{name:e.target.value}:undefined})}/></label>
    <label>Reviewer name<input value={content.reviewer?.name??''} onChange={e=>onChange({...content,reviewer:e.target.value?{name:e.target.value}:undefined})}/></label>
    <label>Last professional review<input type="date" value={content.dates.reviewed??''} onChange={e=>onChange({...content,dates:{...content.dates,reviewed:e.target.value||undefined}})}/></label>
    <label>Lead image<select value={content.hero?.mediaId??''} onChange={e=>onChange({...content,hero:e.target.value?{mediaId:e.target.value,alt:content.hero?.alt??''}:undefined})}><option value="">No image</option>{mediaOptions.map(m=><option value={m.id} key={m.id}>{m.alt} · {m.id.slice(0,8)}</option>)}</select></label>
    {content.hero?<><label>Lead image alt<input value={content.hero.alt} onChange={e=>onChange({...content,hero:{...content.hero!,alt:e.target.value}})}/></label><label>Image caption<input value={content.hero.caption??''} onChange={e=>onChange({...content,hero:{...content.hero!,caption:e.target.value}})}/></label></>:null}
    <h3>References</h3>{content.sources.map((source,i)=><div key={source.id} className={styles.block}><label>Reference label<input value={source.label} onChange={e=>{const sources=[...content.sources];sources[i]={...source,label:e.target.value};onChange({...content,sources})}}/></label><label>Publisher<input value={source.publisher} onChange={e=>{const sources=[...content.sources];sources[i]={...source,publisher:e.target.value};onChange({...content,sources})}}/></label><label>Source URL<input type="url" value={source.url} onChange={e=>{const sources=[...content.sources];sources[i]={...source,url:e.target.value};onChange({...content,sources})}}/></label><label>Checked on<input type="date" value={source.checkedOn} onChange={e=>{const sources=[...content.sources];sources[i]={...source,checkedOn:e.target.value};onChange({...content,sources})}}/></label><button onClick={()=>onChange({...content,sources:content.sources.filter((_,j)=>j!==i)})}>Remove source</button></div>)}
    <button onClick={()=>onChange({...content,sources:[...content.sources,{id:`source-${Date.now()}`,label:'New source',publisher:'Publisher',url:'https://example.com',checkedOn:new Date().toISOString().slice(0,10)}]})}>Add source</button>
    <label>Related reading<select multiple value={content.related.documents} onChange={e=>onChange({...content,related:{...content.related,documents:Array.from(e.target.selectedOptions,o=>o.value)}})}>{relatedOptions.map(item=><option key={item.id} value={item.id}>{item.kind}: {item.title}</option>)}</select></label>
  </section>;
}
export function DocumentEditor({doc,revisions,notes,role,relatedOptions,mediaOptions}:{doc:Doc;revisions:Revision[];notes:Note[];role:string;relatedOptions:{id:string;title:string;kind:string}[];mediaOptions:{id:string;alt:string}[]}){
  const [title,setTitle]=useState(doc.title),[slug,setSlug]=useState(doc.slug),[content,setContent]=useState<DocumentContent>(doc.content),[version,setVersion]=useState(doc.version),[status,setStatus]=useState(doc.status),[message,setMessage]=useState('Saved'),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false);
  const [sessionExpired,setSessionExpired]=useState(false);
  const latest=useRef({title,slug,content,version,dirty,busy});latest.current={title,slug,content,version,dirty,busy};
  function edit(next:DocumentContent){setContent(next);setDirty(true);setMessage('Unsaved changes');}
  function field(key:string,value:string){if(content.kind==='page')edit({...content,fields:{...content.fields,[key]:value}});}
  function common(key:string,value:unknown){if(content.kind!=='page')edit({...content,[key]:value} as DocumentContent);}
  function changeBlock(index:number,block:Block){if(content.kind==='page')return;const blocks=[...content.blocks];blocks[index]=block;common('blocks',blocks);}
  const send=useCallback(async (action:string,extra:Record<string,unknown>={})=>{
    if(latest.current.busy||sessionExpired)return;setBusy(true);setMessage(action==='save'?'Saving…':'Working…');
    const snapshot=latest.current;
    try{const response=await fetch(`/api/studio/documents/${doc.id}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,version:snapshot.version,...(action==='save'?{title:snapshot.title,slug:snapshot.slug,content:snapshot.content}:{}),...extra})});const data=await response.json();if(!response.ok){if(response.status===401){setSessionExpired(true);setMessage('Your session ended. Copy any unsaved changes, then sign in again.');return;}setMessage(response.status===409?'Conflict: another team member saved first. Copy your changes before reloading.':data.error||'Could not save.');return;}
      setVersion(data.result.lock_version);setStatus(data.result.status);if(action==='save'){if(latest.current.title===snapshot.title&&latest.current.slug===snapshot.slug&&latest.current.content===snapshot.content){setDirty(false);setMessage('Saved');}else setMessage('New changes pending…');}else{setMessage(`${action.replace('_',' ')} complete`);window.location.reload();}
    }catch{setMessage('Connection error. Changes remain in this tab.');}finally{setBusy(false);}
  },[doc.id,sessionExpired]);
  useEffect(()=>{if(!dirty||busy||sessionExpired)return;const timer=setTimeout(()=>void send('save'),1800);return()=>clearTimeout(timer);},[title,slug,content,dirty,busy,sessionExpired,send]);
  const preview=`/api/studio/preview?id=${encodeURIComponent(doc.id)}`;
  return <><p className={styles.eyebrow}>{doc.kind} · {status.replace('_',' ')}</p><h1>{title}</h1><div className={styles.toolbar}><a className={styles.button} href={preview} target="_blank" rel="noreferrer">Preview working copy ↗</a><button onClick={()=>void send('save')} disabled={busy||!dirty||sessionExpired}>Save now</button>{content.kind!=='page'?<button disabled={busy||sessionExpired} onClick={async()=>{const response=await fetch('/api/studio/documents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:`${title} copy`,slug:`${slug}-copy`,content,duplicateOf:doc.id})});const data=await response.json();if(response.ok)window.location.assign(`/studio/documents/${data.id}`);else if(response.status===401){setSessionExpired(true);setMessage('Your session ended. Copy any unsaved changes, then sign in again.');}else setMessage(data.error||'Duplicate failed.')}}>Duplicate</button>:null}<span role="status">{message}</span>{sessionExpired?<Link href="/studio/login">Sign in again</Link>:null}</div>
    <div className={styles.editorGrid}><div className={styles.editorMain}><section><h2>Identity</h2><label>Title<input value={title} onChange={e=>{setTitle(e.target.value);setDirty(true)}} maxLength={200}/></label><label>URL slug<input disabled={content.kind==='page'} value={slug} onChange={e=>{setSlug(e.target.value);setDirty(true)}} maxLength={96}/></label></section>
      {content.kind==='page'?<section><h2>Page fields</h2><p>Leave a field empty to keep the current design and copy.</p>{(PAGE_FIELDS[slug as keyof typeof PAGE_FIELDS]??[]).map(key=><label key={key}>{key}<textarea value={content.fields[key]??''} onChange={e=>field(key,e.target.value)}/></label>)}</section>:<><section><h2>Introduction</h2><label>Standfirst<textarea value={content.dek} onChange={e=>common('dek',e.target.value)} /></label><label>Category<input value={content.category} onChange={e=>common('category',e.target.value)}/></label><label>Jurisdiction<input value={content.jurisdiction??''} onChange={e=>common('jurisdiction',e.target.value)}/></label>{content.kind==='article'?<><label>Short answer<textarea value={content.answer??''} onChange={e=>common('answer',e.target.value)}/></label><label>Assumptions, one per line<textarea value={content.assumptions.join('\n')} onChange={e=>common('assumptions',e.target.value.split('\n').filter(Boolean))}/></label></>:<>{(['context','challenge','intervention','outcome'] as const).map(key=><label key={key}>{key}<textarea value={content[key]} onChange={e=>common(key,e.target.value)}/></label>)}<h3>Results</h3>{content.results.map((result,i)=><div className={styles.row} key={i}><input aria-label="Result label" value={result.label} onChange={e=>{const next=[...content.results];next[i]={...result,label:e.target.value};common('results',next)}}/><input aria-label="Value" value={result.value} onChange={e=>{const next=[...content.results];next[i]={...result,value:e.target.value};common('results',next)}}/><input aria-label="Period" value={result.period??''} onChange={e=>{const next=[...content.results];next[i]={...result,period:e.target.value};common('results',next)}}/><select aria-label="Result type" value={result.type} onChange={e=>{const next=[...content.results];next[i]={...result,type:e.target.value as typeof result.type};common('results',next)}}><option value="observed">Observed</option><option value="projected">Projected</option><option value="estimated">Estimated</option></select></div>)}<button onClick={()=>common('results',[...content.results,{label:'New result',value:'—',type:'observed'}])}>Add result</button></>}</section>
      <EditorialFields content={content} onChange={edit} relatedOptions={relatedOptions} mediaOptions={mediaOptions}/><section><h2>Body</h2>{content.blocks.map((block,i)=><div className={styles.block} key={i}><div className={styles.blockHead}><strong>{i+1}. {block.type}</strong><button onClick={()=>common('blocks',content.blocks.filter((_,j)=>i!==j))}>Remove</button></div>{block.type==='paragraph'||block.type==='heading'||block.type==='quote'?<textarea aria-label={`${block.type} ${i+1}`} value={block.text} onChange={e=>changeBlock(i,{...block,text:e.target.value})}/>:null}{block.type==='heading'?<select aria-label="Heading level" value={block.level} onChange={e=>changeBlock(i,{...block,level:Number(e.target.value) as 2|3})}><option value="2">Heading 2</option><option value="3">Heading 3</option></select>:null}{block.type==='list'?<textarea aria-label="List items" value={block.items.join('\n')} onChange={e=>changeBlock(i,{...block,items:e.target.value.split('\n').filter(Boolean)})}/>:null}{block.type==='table'?<textarea aria-label="Table rows, tab separated" value={block.rows.map(r=>r.join('\t')).join('\n')} onChange={e=>changeBlock(i,{...block,rows:e.target.value.split('\n').map(r=>r.split('\t'))})}/>:null}{block.type==='cta'?<><input aria-label="Button label" value={block.label} onChange={e=>changeBlock(i,{...block,label:e.target.value})}/><select aria-label="Button destination" value={block.target} onChange={e=>changeBlock(i,{...block,target:e.target.value as typeof block.target})}>{['contact','booking','investment','purchase','tax','team'].map(v=><option key={v}>{v}</option>)}</select></>:null}{block.type==='image'?<><input aria-label="Media ID" value={block.mediaId} onChange={e=>changeBlock(i,{...block,mediaId:e.target.value})}/><input aria-label="Image alt" value={block.alt} onChange={e=>changeBlock(i,{...block,alt:e.target.value})}/></>:null}{block.type==='source'?<input aria-label="Source ID" value={block.sourceId} onChange={e=>changeBlock(i,{...block,sourceId:e.target.value})}/>:null}</div>)}<div className={styles.row}>{(['paragraph','heading','list','table','quote','image','source','cta'] as const).map(type=><button key={type} onClick={()=>{const defaults:Record<string,Block>={paragraph:{type:'paragraph',text:'New paragraph'},heading:{type:'heading',level:2,text:'New heading'},list:{type:'list',ordered:false,items:['New item']},table:{type:'table',rows:[['Heading'],['Value']]},quote:{type:'quote',text:'New quote'},image:{type:'image',mediaId:'00000000-0000-0000-0000-000000000000',alt:''},source:{type:'source',sourceId:'source'},cta:{type:'cta',label:'Contact Sarah',target:'contact'}};common('blocks',[...content.blocks,defaults[type]])}}>+ {type}</button>)}</div></section>
      <section><h2>SEO and connections</h2><label>SEO mode<select value={content.seo.mode} onChange={e=>common('seo',{...content.seo,mode:e.target.value})}><option value="auto">Automatic</option><option value="custom">Custom</option></select></label>{content.seo.mode==='custom'?<><label>Search title<input value={content.seo.title??''} onChange={e=>common('seo',{...content.seo,title:e.target.value})}/></label><label>Description<textarea value={content.seo.description??''} onChange={e=>common('seo',{...content.seo,description:e.target.value})}/></label></>:null}<label>Related services<select multiple value={content.related.services} onChange={e=>common('related',{...content.related,services:Array.from(e.target.selectedOptions,o=>o.value)})}>{['investment','purchase','tax'].map(v=><option key={v}>{v}</option>)}</select></label></section></>}
    </div><aside className={styles.editorAside}><section><h2>Review</h2><p>Working copy and published version are separate.</p>{status==='blocked'&&role!=='contributor'?<button onClick={()=>void send('unblock')} disabled={busy}>Return to draft for revisions</button>:null}{status==='draft'?<button onClick={()=>void send('submit')} disabled={dirty||busy}>Send to review</button>:null}{role!=='contributor'&&status==='in_review'?<><button onClick={()=>void send('approve')} disabled={dirty||busy}>Approve</button><button onClick={()=>void send('request_changes')} disabled={busy}>Request changes</button></>:null}{role!=='contributor'&&status==='approved'?<button onClick={()=>void send('publish')} disabled={busy}>Publish to preview</button>:null}{role!=='contributor'&&status==='published'?<button onClick={()=>void send('unpublish')} disabled={busy}>Remove from preview</button>:null}</section><section><h2>Versions</h2><ul>{revisions.map(rev=><li key={rev.id}>#{rev.number} · {rev.reason} <button onClick={()=>void send('restore',{revisionId:rev.id})} disabled={busy}>Restore</button></li>)}</ul></section><section><h2>Editorial notes</h2>{notes.filter(n=>!n.resolved).map(note=><p key={note.id}><strong>{note.code} · {note.severity}</strong><br/>{note.body}{role!=='contributor'?<><br/><button onClick={async()=>{const response=await fetch(`/api/studio/notes/${note.id}`,{method:'POST'});if(response.ok)window.location.reload();else setMessage('Could not resolve note.')}}>Mark resolved</button></>:null}</p>)}</section><Link href="/studio">← Back to overview</Link></aside></div></>;
}
